services:
  - type: web
    name: carbonwise-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_backend.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
